# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/zwang563/final-project-null

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/zwang563/final-project-null

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/zwang563/final-project-null/CMakeFiles /home/csmajs/zwang563/final-project-null//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/zwang563/final-project-null/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testingCharacter

# Build rule for target.
testingCharacter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testingCharacter
.PHONY : testingCharacter

# fast build rule for target.
testingCharacter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingCharacter.dir/build.make CMakeFiles/testingCharacter.dir/build
.PHONY : testingCharacter/fast

#=============================================================================
# Target rules for targets named testingFriend

# Build rule for target.
testingFriend: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testingFriend
.PHONY : testingFriend

# fast build rule for target.
testingFriend/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingFriend.dir/build.make CMakeFiles/testingFriend.dir/build
.PHONY : testingFriend/fast

#=============================================================================
# Target rules for targets named testingEnemy

# Build rule for target.
testingEnemy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testingEnemy
.PHONY : testingEnemy

# fast build rule for target.
testingEnemy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingEnemy.dir/build.make CMakeFiles/testingEnemy.dir/build
.PHONY : testingEnemy/fast

#=============================================================================
# Target rules for targets named testingPlayer

# Build rule for target.
testingPlayer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testingPlayer
.PHONY : testingPlayer

# fast build rule for target.
testingPlayer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingPlayer.dir/build.make CMakeFiles/testingPlayer.dir/build
.PHONY : testingPlayer/fast

#=============================================================================
# Target rules for targets named runGame

# Build rule for target.
runGame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runGame
.PHONY : runGame

# fast build rule for target.
runGame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/build
.PHONY : runGame/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

Character/character.o: Character/character.cpp.o
.PHONY : Character/character.o

# target to build an object file
Character/character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingCharacter.dir/build.make CMakeFiles/testingCharacter.dir/Character/character.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingFriend.dir/build.make CMakeFiles/testingFriend.dir/Character/character.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingEnemy.dir/build.make CMakeFiles/testingEnemy.dir/Character/character.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingPlayer.dir/build.make CMakeFiles/testingPlayer.dir/Character/character.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/Character/character.cpp.o
.PHONY : Character/character.cpp.o

Character/character.i: Character/character.cpp.i
.PHONY : Character/character.i

# target to preprocess a source file
Character/character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingCharacter.dir/build.make CMakeFiles/testingCharacter.dir/Character/character.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingFriend.dir/build.make CMakeFiles/testingFriend.dir/Character/character.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingEnemy.dir/build.make CMakeFiles/testingEnemy.dir/Character/character.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingPlayer.dir/build.make CMakeFiles/testingPlayer.dir/Character/character.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/Character/character.cpp.i
.PHONY : Character/character.cpp.i

Character/character.s: Character/character.cpp.s
.PHONY : Character/character.s

# target to generate assembly for a file
Character/character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingCharacter.dir/build.make CMakeFiles/testingCharacter.dir/Character/character.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingFriend.dir/build.make CMakeFiles/testingFriend.dir/Character/character.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingEnemy.dir/build.make CMakeFiles/testingEnemy.dir/Character/character.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingPlayer.dir/build.make CMakeFiles/testingPlayer.dir/Character/character.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/Character/character.cpp.s
.PHONY : Character/character.cpp.s

Character/chartest.o: Character/chartest.cpp.o
.PHONY : Character/chartest.o

# target to build an object file
Character/chartest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingCharacter.dir/build.make CMakeFiles/testingCharacter.dir/Character/chartest.cpp.o
.PHONY : Character/chartest.cpp.o

Character/chartest.i: Character/chartest.cpp.i
.PHONY : Character/chartest.i

# target to preprocess a source file
Character/chartest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingCharacter.dir/build.make CMakeFiles/testingCharacter.dir/Character/chartest.cpp.i
.PHONY : Character/chartest.cpp.i

Character/chartest.s: Character/chartest.cpp.s
.PHONY : Character/chartest.s

# target to generate assembly for a file
Character/chartest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingCharacter.dir/build.make CMakeFiles/testingCharacter.dir/Character/chartest.cpp.s
.PHONY : Character/chartest.cpp.s

Dungeon.o: Dungeon.cpp.o
.PHONY : Dungeon.o

# target to build an object file
Dungeon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/Dungeon.cpp.o
.PHONY : Dungeon.cpp.o

Dungeon.i: Dungeon.cpp.i
.PHONY : Dungeon.i

# target to preprocess a source file
Dungeon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/Dungeon.cpp.i
.PHONY : Dungeon.cpp.i

Dungeon.s: Dungeon.cpp.s
.PHONY : Dungeon.s

# target to generate assembly for a file
Dungeon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/Dungeon.cpp.s
.PHONY : Dungeon.cpp.s

Enemy/enemy.o: Enemy/enemy.cpp.o
.PHONY : Enemy/enemy.o

# target to build an object file
Enemy/enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingEnemy.dir/build.make CMakeFiles/testingEnemy.dir/Enemy/enemy.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/Enemy/enemy.cpp.o
.PHONY : Enemy/enemy.cpp.o

Enemy/enemy.i: Enemy/enemy.cpp.i
.PHONY : Enemy/enemy.i

# target to preprocess a source file
Enemy/enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingEnemy.dir/build.make CMakeFiles/testingEnemy.dir/Enemy/enemy.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/Enemy/enemy.cpp.i
.PHONY : Enemy/enemy.cpp.i

Enemy/enemy.s: Enemy/enemy.cpp.s
.PHONY : Enemy/enemy.s

# target to generate assembly for a file
Enemy/enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingEnemy.dir/build.make CMakeFiles/testingEnemy.dir/Enemy/enemy.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/Enemy/enemy.cpp.s
.PHONY : Enemy/enemy.cpp.s

Enemy/enemytester.o: Enemy/enemytester.cpp.o
.PHONY : Enemy/enemytester.o

# target to build an object file
Enemy/enemytester.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingEnemy.dir/build.make CMakeFiles/testingEnemy.dir/Enemy/enemytester.cpp.o
.PHONY : Enemy/enemytester.cpp.o

Enemy/enemytester.i: Enemy/enemytester.cpp.i
.PHONY : Enemy/enemytester.i

# target to preprocess a source file
Enemy/enemytester.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingEnemy.dir/build.make CMakeFiles/testingEnemy.dir/Enemy/enemytester.cpp.i
.PHONY : Enemy/enemytester.cpp.i

Enemy/enemytester.s: Enemy/enemytester.cpp.s
.PHONY : Enemy/enemytester.s

# target to generate assembly for a file
Enemy/enemytester.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingEnemy.dir/build.make CMakeFiles/testingEnemy.dir/Enemy/enemytester.cpp.s
.PHONY : Enemy/enemytester.cpp.s

Friendly/friendly.o: Friendly/friendly.cpp.o
.PHONY : Friendly/friendly.o

# target to build an object file
Friendly/friendly.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingFriend.dir/build.make CMakeFiles/testingFriend.dir/Friendly/friendly.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingPlayer.dir/build.make CMakeFiles/testingPlayer.dir/Friendly/friendly.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/Friendly/friendly.cpp.o
.PHONY : Friendly/friendly.cpp.o

Friendly/friendly.i: Friendly/friendly.cpp.i
.PHONY : Friendly/friendly.i

# target to preprocess a source file
Friendly/friendly.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingFriend.dir/build.make CMakeFiles/testingFriend.dir/Friendly/friendly.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingPlayer.dir/build.make CMakeFiles/testingPlayer.dir/Friendly/friendly.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/Friendly/friendly.cpp.i
.PHONY : Friendly/friendly.cpp.i

Friendly/friendly.s: Friendly/friendly.cpp.s
.PHONY : Friendly/friendly.s

# target to generate assembly for a file
Friendly/friendly.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingFriend.dir/build.make CMakeFiles/testingFriend.dir/Friendly/friendly.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingPlayer.dir/build.make CMakeFiles/testingPlayer.dir/Friendly/friendly.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/Friendly/friendly.cpp.s
.PHONY : Friendly/friendly.cpp.s

Friendly/testFriend.o: Friendly/testFriend.cpp.o
.PHONY : Friendly/testFriend.o

# target to build an object file
Friendly/testFriend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingFriend.dir/build.make CMakeFiles/testingFriend.dir/Friendly/testFriend.cpp.o
.PHONY : Friendly/testFriend.cpp.o

Friendly/testFriend.i: Friendly/testFriend.cpp.i
.PHONY : Friendly/testFriend.i

# target to preprocess a source file
Friendly/testFriend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingFriend.dir/build.make CMakeFiles/testingFriend.dir/Friendly/testFriend.cpp.i
.PHONY : Friendly/testFriend.cpp.i

Friendly/testFriend.s: Friendly/testFriend.cpp.s
.PHONY : Friendly/testFriend.s

# target to generate assembly for a file
Friendly/testFriend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingFriend.dir/build.make CMakeFiles/testingFriend.dir/Friendly/testFriend.cpp.s
.PHONY : Friendly/testFriend.cpp.s

GameMaster.o: GameMaster.cpp.o
.PHONY : GameMaster.o

# target to build an object file
GameMaster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/GameMaster.cpp.o
.PHONY : GameMaster.cpp.o

GameMaster.i: GameMaster.cpp.i
.PHONY : GameMaster.i

# target to preprocess a source file
GameMaster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/GameMaster.cpp.i
.PHONY : GameMaster.cpp.i

GameMaster.s: GameMaster.cpp.s
.PHONY : GameMaster.s

# target to generate assembly for a file
GameMaster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/GameMaster.cpp.s
.PHONY : GameMaster.cpp.s

GameText.o: GameText.cpp.o
.PHONY : GameText.o

# target to build an object file
GameText.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/GameText.cpp.o
.PHONY : GameText.cpp.o

GameText.i: GameText.cpp.i
.PHONY : GameText.i

# target to preprocess a source file
GameText.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/GameText.cpp.i
.PHONY : GameText.cpp.i

GameText.s: GameText.cpp.s
.PHONY : GameText.s

# target to generate assembly for a file
GameText.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/GameText.cpp.s
.PHONY : GameText.cpp.s

Player/Player.o: Player/Player.cpp.o
.PHONY : Player/Player.o

# target to build an object file
Player/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingPlayer.dir/build.make CMakeFiles/testingPlayer.dir/Player/Player.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/Player/Player.cpp.o
.PHONY : Player/Player.cpp.o

Player/Player.i: Player/Player.cpp.i
.PHONY : Player/Player.i

# target to preprocess a source file
Player/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingPlayer.dir/build.make CMakeFiles/testingPlayer.dir/Player/Player.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/Player/Player.cpp.i
.PHONY : Player/Player.cpp.i

Player/Player.s: Player/Player.cpp.s
.PHONY : Player/Player.s

# target to generate assembly for a file
Player/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingPlayer.dir/build.make CMakeFiles/testingPlayer.dir/Player/Player.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/Player/Player.cpp.s
.PHONY : Player/Player.cpp.s

Player/playertest.o: Player/playertest.cpp.o
.PHONY : Player/playertest.o

# target to build an object file
Player/playertest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingPlayer.dir/build.make CMakeFiles/testingPlayer.dir/Player/playertest.cpp.o
.PHONY : Player/playertest.cpp.o

Player/playertest.i: Player/playertest.cpp.i
.PHONY : Player/playertest.i

# target to preprocess a source file
Player/playertest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingPlayer.dir/build.make CMakeFiles/testingPlayer.dir/Player/playertest.cpp.i
.PHONY : Player/playertest.cpp.i

Player/playertest.s: Player/playertest.cpp.s
.PHONY : Player/playertest.s

# target to generate assembly for a file
Player/playertest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testingPlayer.dir/build.make CMakeFiles/testingPlayer.dir/Player/playertest.cpp.s
.PHONY : Player/playertest.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runGame.dir/build.make CMakeFiles/runGame.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... runGame"
	@echo "... testingCharacter"
	@echo "... testingEnemy"
	@echo "... testingFriend"
	@echo "... testingPlayer"
	@echo "... Character/character.o"
	@echo "... Character/character.i"
	@echo "... Character/character.s"
	@echo "... Character/chartest.o"
	@echo "... Character/chartest.i"
	@echo "... Character/chartest.s"
	@echo "... Dungeon.o"
	@echo "... Dungeon.i"
	@echo "... Dungeon.s"
	@echo "... Enemy/enemy.o"
	@echo "... Enemy/enemy.i"
	@echo "... Enemy/enemy.s"
	@echo "... Enemy/enemytester.o"
	@echo "... Enemy/enemytester.i"
	@echo "... Enemy/enemytester.s"
	@echo "... Friendly/friendly.o"
	@echo "... Friendly/friendly.i"
	@echo "... Friendly/friendly.s"
	@echo "... Friendly/testFriend.o"
	@echo "... Friendly/testFriend.i"
	@echo "... Friendly/testFriend.s"
	@echo "... GameMaster.o"
	@echo "... GameMaster.i"
	@echo "... GameMaster.s"
	@echo "... GameText.o"
	@echo "... GameText.i"
	@echo "... GameText.s"
	@echo "... Player/Player.o"
	@echo "... Player/Player.i"
	@echo "... Player/Player.s"
	@echo "... Player/playertest.o"
	@echo "... Player/playertest.i"
	@echo "... Player/playertest.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

